version: "3.9"
services:
  db:
    image: postgres:16
    container_name: zenbucks_postgres
    environment:
      POSTGRES_USER: zenbucks
      POSTGRES_PASSWORD: zenbucks_pw
      POSTGRES_DB: zenbucksdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: zenbucks_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
